# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "carrier"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["stanislaw"]
  s.date = "2012-04-05"
  s.description = "Raw github-like messaging system to reuse across Rails apps. Acts as Rails 3.1 mountable engine. Fast and robust."
  s.email = "s.pankevich@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/assets/images/.gitkeep",
    "app/assets/images/carrier/chosen-sprite.png",
    "app/assets/javascripts/carrier/chosen.jquery.min.js",
    "app/assets/javascripts/carrier/chosen.js",
    "app/assets/javascripts/jquery.min.js",
    "app/assets/javascripts/rails.js",
    "app/assets/stylesheets/carrier/carrier.css",
    "app/assets/stylesheets/carrier/chosen.css",
    "app/controllers/carrier/application_controller.rb",
    "app/controllers/carrier/chains_controller.rb",
    "app/controllers/carrier/messages_controller.rb",
    "app/helpers/carrier/application_helper.rb",
    "app/models/carrier/chain.rb",
    "app/models/carrier/message.rb",
    "app/models/carrier/message/scopes.rb",
    "app/models/carrier/message/subject.rb",
    "app/models/carrier/message/validations.rb",
    "app/validators/recipients/exclude_self.rb",
    "app/validators/recipients/recipients_presence_validator.rb",
    "app/validators/recipients/right_recipients_validator.rb",
    "app/views/carrier/chains/archive.js.erb",
    "app/views/carrier/chains/unarchive.js.erb",
    "app/views/carrier/messages/_archive_chain.html.erb",
    "app/views/carrier/messages/_chosen.html.erb",
    "app/views/carrier/messages/_form.html.erb",
    "app/views/carrier/messages/_head.html.erb",
    "app/views/carrier/messages/_index_message.html.erb",
    "app/views/carrier/messages/_message.html.erb",
    "app/views/carrier/messages/_nav_messages.html.erb",
    "app/views/carrier/messages/_recipients.html.erb",
    "app/views/carrier/messages/_reply.html.erb",
    "app/views/carrier/messages/as_sent.html.erb",
    "app/views/carrier/messages/create.js.erb",
    "app/views/carrier/messages/index.html.erb",
    "app/views/carrier/messages/new.html.erb",
    "app/views/carrier/messages/new.js.erb",
    "app/views/carrier/messages/reply.js.erb",
    "app/views/carrier/messages/show.html.erb",
    "app/views/layouts/carrier/application.html.erb",
    "app/views/partials/_error_messages_for.html.erb",
    "carrier.gemspec",
    "config/locales/carrier.en.yml",
    "config/locales/carrier.ru.yml",
    "config/routes.rb",
    "db/migrate/001_create_messages.rb",
    "db/migrate/002_create_chains.rb",
    "db/migrate/003_create_read_marks",
    "lib/carrier.rb",
    "lib/carrier/configuration.rb",
    "lib/carrier/configuration/models.rb",
    "lib/carrier/configuration/routes.rb",
    "lib/carrier/configuration/user.rb",
    "lib/carrier/rails.rb",
    "lib/carrier/rails/engine.rb",
    "lib/carrier/rails/helpers.rb",
    "lib/carrier/version.rb",
    "lib/tasks/carrier_tasks.rake",
    "spec/carrier/app/controllers/application_controller_spec.rb",
    "spec/carrier/app/models/message_scopes_spec.rb",
    "spec/carrier/app/models/message_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/javascripts/default.js",
    "spec/dummy/app/assets/javascripts/jquery.js",
    "spec/dummy/app/assets/javascripts/jquery_ujs.js",
    "spec/dummy/app/assets/javascripts/posts.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/assets/stylesheets/default.css",
    "spec/dummy/app/assets/stylesheets/posts.css",
    "spec/dummy/app/assets/stylesheets/scaffold.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/default_controller.rb",
    "spec/dummy/app/controllers/posts_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/default_helper.rb",
    "spec/dummy/app/helpers/posts_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/app/views/default/index.html.erb",
    "spec/dummy/app/views/devise/confirmations/new.html.erb",
    "spec/dummy/app/views/devise/mailer/confirmation_instructions.html.erb",
    "spec/dummy/app/views/devise/mailer/reset_password_instructions.html.erb",
    "spec/dummy/app/views/devise/mailer/unlock_instructions.html.erb",
    "spec/dummy/app/views/devise/passwords/edit.html.erb",
    "spec/dummy/app/views/devise/passwords/new.html.erb",
    "spec/dummy/app/views/devise/registrations/edit.html.erb",
    "spec/dummy/app/views/devise/registrations/new.html.erb",
    "spec/dummy/app/views/devise/sessions/new.html.erb",
    "spec/dummy/app/views/devise/shared/_links.erb",
    "spec/dummy/app/views/devise/unlocks/new.html.erb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/posts/_form.html.erb",
    "spec/dummy/app/views/posts/edit.html.erb",
    "spec/dummy/app/views/posts/index.html.erb",
    "spec/dummy/app/views/posts/new.html.erb",
    "spec/dummy/app/views/posts/show.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/cucumber.yml",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/database_mysql.yml",
    "spec/dummy/config/database_pgsql.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/carrier.rb",
    "spec/dummy/config/initializers/devise.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/devise.en.yml",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/007_devise_create_users.rb",
    "spec/dummy/db/migrate/20110130210000_create_read_marks.rb",
    "spec/dummy/db/migrate/20110814064637_create_posts.rb",
    "spec/dummy/db/migrate/20110814164228_create_messages.rb",
    "spec/dummy/db/migrate/20110814164229_create_chains.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/seeds.rb",
    "spec/dummy/factories/message.rb",
    "spec/dummy/factories/user.rb",
    "spec/dummy/features/carrier.feature",
    "spec/dummy/features/step_definitions/debug_steps.rb",
    "spec/dummy/features/step_definitions/resources_steps.rb",
    "spec/dummy/features/step_definitions/web_steps.rb",
    "spec/dummy/features/support/carrier_routes_helper.rb",
    "spec/dummy/features/support/env.rb",
    "spec/dummy/features/support/paths.rb",
    "spec/dummy/features/support/rails_helper.rb",
    "spec/dummy/features/support/singleton.rb",
    "spec/dummy/features/support/transaction.rb",
    "spec/dummy/lib/tasks/cucumber.rake",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/script/cucumber",
    "spec/dummy/script/rails",
    "spec/dummy/test/fixtures/posts.yml",
    "spec/dummy/test/fixtures/users.yml",
    "spec/dummy/test/functional/default_controller_test.rb",
    "spec/dummy/test/functional/posts_controller_test.rb",
    "spec/dummy/test/unit/helpers/default_helper_test.rb",
    "spec/dummy/test/unit/helpers/posts_helper_test.rb",
    "spec/dummy/test/unit/post_test.rb",
    "spec/dummy/test/unit/user_test.rb",
    "spec/dummy_spec_helper.rb",
    "spec/requests/main_spec.rb",
    "spec/support/controller_macros.rb",
    "spec/support/factories.rb",
    "spec/support/rspec_helpers.rb"
  ]
  s.homepage = "http://github.com/stanislaw/carrier"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "Raw github-like messaging system to reuse across Rails apps"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<require_all>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<unread>, [">= 0"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0"])
      s.add_runtime_dependency(%q<sweetloader>, [">= 0"])
      s.add_development_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<rake-kit>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rails>, ["= 3.2.2"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<cutter>, [">= 0"])
    else
      s.add_dependency(%q<require_all>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<unread>, [">= 0"])
      s.add_dependency(%q<sugar-high>, [">= 0"])
      s.add_dependency(%q<sweetloader>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<rake-kit>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rails>, ["= 3.2.2"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<cutter>, [">= 0"])
    end
  else
    s.add_dependency(%q<require_all>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<unread>, [">= 0"])
    s.add_dependency(%q<sugar-high>, [">= 0"])
    s.add_dependency(%q<sweetloader>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<rake-kit>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rails>, ["= 3.2.2"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<cutter>, [">= 0"])
  end
end

