# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "carrier"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["stanislaw"]
  s.date = "2011-11-14"
  s.description = "Raw github-like messaging system to reuse across Rails apps. Acts as Rails 3.1 mountable engine. Fast and robust."
  s.email = "s.pankevich@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/assets/images/.gitkeep",
    "app/assets/javascripts/autocomplete.js",
    "app/assets/javascripts/autocomplete/i18n/jquery-ui-i18n.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-af.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ar-DZ.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ar.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-az.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-bg.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-bs.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ca.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-cs.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-da.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-de.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-el.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-en-AU.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-en-GB.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-en-NZ.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-eo.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-es.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-et.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-eu.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-fa.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-fi.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-fo.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-fr-CH.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-fr.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-gl.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-he.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-hr.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-hu.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-hy.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-id.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-is.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-it.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ja.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ko.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-kz.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-lt.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-lv.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ml.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ms.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-nl.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-no.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-pl.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-pt-BR.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-pt.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-rm.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ro.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ru.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sk.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sl.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sq.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sr-SR.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sr.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-sv.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-ta.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-th.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-tj.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-tr.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-uk.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-vi.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-zh-CN.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-zh-HK.js",
    "app/assets/javascripts/autocomplete/i18n/jquery.ui.datepicker-zh-TW.js",
    "app/assets/javascripts/autocomplete/jquery.ui.autocomplete.min.js",
    "app/assets/javascripts/autocomplete/jquery.ui.core.min.js",
    "app/assets/javascripts/autocomplete/jquery.ui.position.min.js",
    "app/assets/javascripts/autocomplete/jquery.ui.widget.min.js",
    "app/assets/javascripts/carrier.js",
    "app/assets/javascripts/jquery.min.js",
    "app/assets/javascripts/rails.js",
    "app/assets/javascripts/rich-multiselect/jquery-ui.min.js",
    "app/assets/javascripts/rich-multiselect/locale/ui-multiselect-de.js",
    "app/assets/javascripts/rich-multiselect/locale/ui-multiselect-en.js",
    "app/assets/javascripts/rich-multiselect/locale/ui-multiselect-es.js",
    "app/assets/javascripts/rich-multiselect/locale/ui-multiselect-fr.js",
    "app/assets/javascripts/rich-multiselect/locale/ui-multiselect-it.js",
    "app/assets/javascripts/rich-multiselect/plugins/localisation/jquery.localisation-min.js",
    "app/assets/javascripts/rich-multiselect/plugins/localisation/jquery.localisation-pack.js",
    "app/assets/javascripts/rich-multiselect/plugins/localisation/jquery.localisation.js",
    "app/assets/javascripts/rich-multiselect/plugins/scrollTo/README.txt",
    "app/assets/javascripts/rich-multiselect/plugins/scrollTo/changes.txt",
    "app/assets/javascripts/rich-multiselect/plugins/scrollTo/jquery.scrollTo-min.js",
    "app/assets/javascripts/rich-multiselect/plugins/scrollTo/jquery.scrollTo.js",
    "app/assets/javascripts/rich-multiselect/ui.multiselect.js",
    "app/assets/stylesheets/carrier.css",
    "app/assets/stylesheets/carrier_rich.css",
    "app/assets/stylesheets/carrier_simple.css",
    "app/assets/stylesheets/rich-multiselect/ui.multiselect.css",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_55_fbf9ee_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_65_ffffff_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_75_cccccc_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_75_dadada_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_75_e6e6e6_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_75_ffffff_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-bg_flat_95_fef1ec_40x100.png",
    "app/assets/stylesheets/ui-lightness/images/ui-icons_222222_256x240.png",
    "app/assets/stylesheets/ui-lightness/images/ui-icons_2e83ff_256x240.png",
    "app/assets/stylesheets/ui-lightness/images/ui-icons_454545_256x240.png",
    "app/assets/stylesheets/ui-lightness/images/ui-icons_888888_256x240.png",
    "app/assets/stylesheets/ui-lightness/images/ui-icons_cd0a0a_256x240.png",
    "app/assets/stylesheets/ui-lightness/jquery-ui-1.8.14.custom.css",
    "app/controllers/carrier/application_controller.rb",
    "app/controllers/carrier/chains_controller.rb",
    "app/controllers/carrier/messages_controller.rb",
    "app/helpers/carrier/application_helper.rb",
    "app/helpers/carrier/post_helper.rb",
    "app/models/carrier/chain.rb",
    "app/models/carrier/message.rb",
    "app/models/carrier/message/scopes.rb",
    "app/models/carrier/message/subject.rb",
    "app/models/carrier/message/validations.rb",
    "app/validators/recipients/exclude_self.rb",
    "app/validators/recipients/recipients_validator.rb",
    "app/views/carrier/chains/archive.js.erb",
    "app/views/carrier/chains/unarchive.js.erb",
    "app/views/carrier/messages/_archive_chain.html.erb",
    "app/views/carrier/messages/_form.html.erb",
    "app/views/carrier/messages/_head.html.erb",
    "app/views/carrier/messages/_index_message.html.erb",
    "app/views/carrier/messages/_message_collapsed.html.erb",
    "app/views/carrier/messages/_message_expanded.html.erb",
    "app/views/carrier/messages/_nav_messages.html.erb",
    "app/views/carrier/messages/_reply.html.erb",
    "app/views/carrier/messages/as_sent.html.erb",
    "app/views/carrier/messages/collapsed.js.erb",
    "app/views/carrier/messages/create.js.erb",
    "app/views/carrier/messages/expanded.js.erb",
    "app/views/carrier/messages/index.html.erb",
    "app/views/carrier/messages/new.html.erb",
    "app/views/carrier/messages/new.js.erb",
    "app/views/carrier/messages/reply.js.erb",
    "app/views/carrier/messages/rich/_multiselect.html.erb",
    "app/views/carrier/messages/rich/_recipients.html.erb",
    "app/views/carrier/messages/show.html.erb",
    "app/views/carrier/messages/simple/_autocomplete.html.erb",
    "app/views/carrier/messages/simple/_autocomplete_includes.html.erb",
    "app/views/carrier/messages/simple/_recipients.html.erb",
    "app/views/layouts/carrier/application.html.erb",
    "app/views/partials/_error_messages_for.html.erb",
    "carrier.gemspec",
    "config/locales/carrier.en.yml",
    "config/locales/carrier.ru.yml",
    "config/routes.rb",
    "db/migrate/001_create_messages.rb",
    "db/migrate/002_create_chains.rb",
    "db/migrate/003_create_read_marks",
    "lib/carrier.rb",
    "lib/carrier/configuration.rb",
    "lib/carrier/configuration/models.rb",
    "lib/carrier/configuration/ui.rb",
    "lib/carrier/configuration/user.rb",
    "lib/carrier/rails.rb",
    "lib/carrier/rails/engine.rb",
    "lib/carrier/rails/helpers.rb",
    "lib/tasks/carrier_tasks.rake",
    "script/rails",
    "spec/carrier/app/controllers/application_controller_spec.rb",
    "spec/carrier/app/models/message_scopes_spec.rb",
    "spec/carrier/app/models/message_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/javascripts/default.js",
    "spec/dummy/app/assets/javascripts/jquery.js",
    "spec/dummy/app/assets/javascripts/jquery_ujs.js",
    "spec/dummy/app/assets/javascripts/posts.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/assets/stylesheets/default.css",
    "spec/dummy/app/assets/stylesheets/posts.css",
    "spec/dummy/app/assets/stylesheets/scaffold.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/default_controller.rb",
    "spec/dummy/app/controllers/posts_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/default_helper.rb",
    "spec/dummy/app/helpers/posts_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/app/views/default/index.html.erb",
    "spec/dummy/app/views/devise/confirmations/new.html.erb",
    "spec/dummy/app/views/devise/mailer/confirmation_instructions.html.erb",
    "spec/dummy/app/views/devise/mailer/reset_password_instructions.html.erb",
    "spec/dummy/app/views/devise/mailer/unlock_instructions.html.erb",
    "spec/dummy/app/views/devise/passwords/edit.html.erb",
    "spec/dummy/app/views/devise/passwords/new.html.erb",
    "spec/dummy/app/views/devise/registrations/edit.html.erb",
    "spec/dummy/app/views/devise/registrations/new.html.erb",
    "spec/dummy/app/views/devise/sessions/new.html.erb",
    "spec/dummy/app/views/devise/shared/_links.erb",
    "spec/dummy/app/views/devise/unlocks/new.html.erb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/posts/_form.html.erb",
    "spec/dummy/app/views/posts/edit.html.erb",
    "spec/dummy/app/views/posts/index.html.erb",
    "spec/dummy/app/views/posts/new.html.erb",
    "spec/dummy/app/views/posts/show.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/database_mysql.yml",
    "spec/dummy/config/database_pgsql.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/carrier.rb",
    "spec/dummy/config/initializers/devise.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/devise.en.yml",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/007_devise_create_users.rb",
    "spec/dummy/db/migrate/20110130210000_create_read_marks.rb",
    "spec/dummy/db/migrate/20110814064637_create_posts.rb",
    "spec/dummy/db/migrate/20110814164228_create_messages.rb",
    "spec/dummy/db/migrate/20110814164229_create_chains.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/seeds.rb",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/script/rails",
    "spec/dummy/test/fixtures/posts.yml",
    "spec/dummy/test/fixtures/users.yml",
    "spec/dummy/test/functional/default_controller_test.rb",
    "spec/dummy/test/functional/posts_controller_test.rb",
    "spec/dummy/test/unit/helpers/default_helper_test.rb",
    "spec/dummy/test/unit/helpers/posts_helper_test.rb",
    "spec/dummy/test/unit/post_test.rb",
    "spec/dummy/test/unit/user_test.rb",
    "spec/dummy_spec_helper.rb",
    "spec/integration/carrier_spec.rb",
    "spec/requests/main_spec.rb",
    "spec/support/controller_macros.rb",
    "spec/support/factories.rb",
    "spec/support/rspec_helpers.rb",
    "test/helper.rb",
    "test/test_carrier.rb"
  ]
  s.homepage = "http://github.com/stanislaw/carrier"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Raw github-like messaging system to reuse across Rails apps"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<require_all>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<unread>, [">= 0"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0"])
      s.add_runtime_dependency(%q<sweetloader>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 3.1.0"])
      s.add_development_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<rake-kit>, [">= 0"])
      s.add_development_dependency(%q<cutter>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.5"])
    else
      s.add_dependency(%q<require_all>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<unread>, [">= 0"])
      s.add_dependency(%q<sugar-high>, [">= 0"])
      s.add_dependency(%q<sweetloader>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rake-kit>, [">= 0"])
      s.add_dependency(%q<cutter>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rspec-rails>, [">= 2.5"])
    end
  else
    s.add_dependency(%q<require_all>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<unread>, [">= 0"])
    s.add_dependency(%q<sugar-high>, [">= 0"])
    s.add_dependency(%q<sweetloader>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rake-kit>, [">= 0"])
    s.add_dependency(%q<cutter>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rspec-rails>, [">= 2.5"])
  end
end

