development:
  adapter:  mysql2
  host:     localhost
  database: carrier_development
  username: root 
  password: 
  encoding: utf8

test: &test
  adapter:  mysql2
  host:     localhost
  database: carrier_test
  username: root
  password: 
  encoding: utf8

production:
  adapter:  mysql2
  host:     localhost
  database: carrier_production
  username: root 
  password: root 
  encoding: utf8

cucumber:
  <<: *test
